name: screens
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  intl: ^0.18.1
  syncfusion_flutter_charts: ^22.2.9
  velocity_x: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
